site_name: Catálogo de Interoperabilidade
theme: mkdocs
theme_dir: default_ptbr
repo_url: https://github.com/govbr/catalogo-govbr/
site_description: Catálogo de Serviços interoperáveis do Governo Federal Brasileiro.
copyright: CC0
repo_name: <i class="fa fa-github"></i> Contribua com os serviços
extra_css:
  - css/extra.css
